### ISSUE TITLE
Rename 'master' branch

### ISSUE THREAD

**Issue by AshtonDavis** [AshtonDavis/open-source-transition-resources#7]
In keeping with Red Hat's conscious language initiative, we should rename files and branches using the word 'master' to remove it from the project.

**Comment by CodePoetSarah** [comment]
I took a look at how to do this and I don't think I can change it, only the owner. From reading it looks simple to do, from the repository settings you can change "master" to "main".

**Comment by CodePoetSarah** [comment]
I have created a new branch called "main" which is the new default for github repos. @AshtonDavis can you go into settings and change the default branch from master to main and then remove the master branch.

**Comment by CodePoetSarah** [comment]
Thanks,  we can close this now.
