### ISSUE TITLE
Website Template Broken on Home

### ISSUE THREAD

**Issue by CodePoetSarah** [AshtonDavis/open-source-transition-resources#8]
Doing a clean pull on the website and running Hugo returns a blank homepage. So I need to fix the template :-)

**Comment by AshtonDavis** [comment]
Oh no! When I tested before my last commit things worked fine. Sorry if I broke something.

**Comment by CodePoetSarah** [comment]
I don't know if it was the website template, I think I need to upgrade the theme files. I'll look at it this weekend.

**Comment by CodePoetSarah** [comment]
D'Oh ... it was me :-)

I just noticed the theme is a submodule, so I need to pull the theme for my local setup in order to build the website.

Sometimes this computer / technology thing is beyond me at times ...

**Comment by CodePoetSarah** [comment]
Really helps if I read the documentation ... that I wrote ... but completely forgot about :-)
The website works fine. 

I will do some website updates this weekend.
