### ISSUE TITLE
Add Vocal section

### ISSUE THREAD

**Issue by DanikaRoseRaven** [AshtonDavis/open-source-transition-resources#9]
There should be a section for vocal work and resrouces. 

One of the better resources has been 
https://www.youtube.com/channel/UCBYlEnfAUbrYSwF0VujcmHA

Zheetha also has a Discord server which is accessible via her Patreon.

**Comment by CodePoetSarah** [comment]
Thanks Dankika, this is awesome. I will also add a discord and slack section so we can build there as well.

**Comment by CodePoetSarah** [comment]
Added the section and rebuilt the PDF's - I'll close this out when I have information on Zheetha's Patreon.

**Comment by CodePoetSarah** [comment]
Closing this for now, if we have resources to add, we can open a new ticket :-) the vocal section is now on all guides.
